#!/bin/bash

# This script is to make my life easier when building AOKP kangs. It  #
# will build for all the One V devices, but can be modified for       #
# others.                                                             #
# If you want to use this build script you will need to change quite  #
# A few things, including the DIR, sync -jx, device name, upload url, #
# etc. Have fun building!                                             #

HOME=~/android/4.2

# Starting Timer for build
start() {
START=$(date +%s)
}

# Clean out old builds
cd $HOME
. build/envsetup.sh
clear

sync() {
echo -n "would you like to sync yourself? (y/n)? "
read que

if [ "$que" == "y" ]; then
repo sync -j10
else
echo "you better be sure"
fi
}

clean(){
echo -n "would you like to clean yourself? (y/n)? "
read que

if [ "$que" == "y" ]; then
make clobber && make clean
rm -rf out
cd $HOME
else
echo "you better be sure"
fi
}

# Reverts
Wifi() {
cd $HOME
cd frameworks/base
git fetch https://github.com/rukin5197/android_frameworks_base.git refs/heads/cm-10.1 && git cherry-pick 8b035f4f273067c56639adda5f23ebba8d9ff1f5
cd $HOME
}


# Cherries
VideoCamera() {
cd $HOME
cd frameworks/av
git fetch https://github.com/rukin5197/android_frameworks_av/
git cherry-pick c5c2b285e19b3a007d25b7eafaaf913837892c84
cd $HOME
cd hardware/qcom/media
git fetch https://github.com/rukin5197/hardware_qcom_media/
git cherry-pick 5bab33bef04b4d9593127d81b6f7038ff81fea37
cd $HOME
}

# Uploads
uploadprimoc() {
cd $HOME
cd out/target/product/primoc
scp -P 2222 cm-10.1-* gannon5197@upload.goo.im:~/public_html/cm10.1/primoc/nightlies/
cd $HOME
}

uploadprimou() {
cd $HOME
cd out/target/product/primou
scp -P 2222 cm-10.1-* gannon5197@upload.goo.im:~/public_html/cm10.1/primou/nightlies/
cd $HOME
}

end() {
END=$(date +%s)
ELAPSED=$((END - START))
E_MIN=$((ELAPSED / 60))
E_SEC=$((ELAPSED - E_MIN * 60))
printf "Elapsed: "
[ $E_MIN != 0 ] && printf "%d min(s) " $E_MIN
printf "%d sec(s)\n" $E_SEC
}

while :
do
clear
echo " Which device are you building for today?"
echo "1. PrimoC"
echo "2. PrimoU"
echo "3. Exit"
echo -n "Please enter option [1 - 3]"
read opt
case $opt in
1) echo "************* Building PrimoC *************";
sync;
clean;
start;
Wifi;
brunch primoc 2>&1 | tee cm_primoc.log;
uploadprimoc;
end;
pause;;
2) echo "************* Building PrimoU *************";
sync;
clean;
start;
Wifi;
brunch primou 2>&1 | tee cm_primou.log;
uploadprimou;
end;
pause;;
4) echo "Bye!"
exit 1;;
*) echo "$opt is an invaild option. Please select option between 1-3 only";
echo "Press [enter] key to continue. . .";
read enterKey;;
esac
done
