#!/bin/bash
#

HOME=~/android/aokpjb
cd $HOME
echo "This is my cherry-picks. Run after repo sync if needed"
while:
do
clear
echo " Which Cherry-picks you want today?"
echo "1. Hardware Keys"
echo "2. Lockscreen Targets"
echo "3. Both"
echo -n "Please enter option [1 - 3]"
read opt
case $opt in
1) echo "************* Doing hardware keys *********";
cd packages/apps/ROMControl
git fetch http://gerrit.sudoservers.com/AOKP/frameworks_base refs/changes/47/3147/7 && git cherry-pick FETCH_HEAD
cd $HOME
cd frameworks/base
git fetch http://gerrit.sudoservers.com/AOKP/frameworks_base refs/changes/47/3147/7 && git cherry-pick FETCH_HEAD
cd $HOME
end;
pause;;
2) echo "************ Doing Lockscreen Targets ********";
cd packages/apps/ROMControl
git fetch http://gerrit.sudoservers.com/AOKP/packages_apps_ROMControl refs/changes/37/2837/16 && git cherry-pick FETCH_HEAD
cd $HOME

3) echo "********* Doing Lockscreen Targets and Hardware Keys ********"
cd packages/apps/ROMControl
git fetch http://gerrit.sudoservers.com/AOKP/packages_apps_ROMControl refs/chan$
cd $HOME
cd frameworks/base
git fetch http://gerrit.sudoservers.com/AOKP/frameworks_base refs/changes/47/31$
cd $HOME
cd packages/apps/ROMControl
git fetch http://gerrit.sudoservers.com/AOKP/packages_apps_ROMControl refs/chan$
cd $HOME
