#!/bin/bash
#

HOME=~/android/aokpjb


echo "Merging with my local tree. Let's hope this doesn't cause errors"

cd $HOME
cd device/htc/primoc
git checkout jb
git fetch upstream
git merge upstream/jellybean

cd $HOME
cd device/htc/primou
git checkout jb
git add .
git commit -m "Automatic Commit"
git fetch upstream
git merge upstream/jellybean
git commit -m "Merge branch upstream/jellybean into jellybean"
git push -f origin

cd $HOME
cd vendor/htc
git add .
git commit -m "Automatic Commit"
git push -f origin
