#!/bin/bash

# This script is to make my life easier when building AOKP kangs. It  #
# will build for all the One V devices, but can be modified for       #
# others.                                                             #
# If you want to use this build script you will need to change quite  #
# A few things, including the DIR, sync -jx, device name, upload url, #
# etc. Have fun building!                                             #

HOME=~/android/slim

# Starting Timer for build
start() {
START=$(date +%s)
}

# Clean out old builds
cd $HOME
. build/envsetup.sh
clear

sync() {
echo -n "would you like to sync yourself? (y/n)? "
read que

if [ "$que" == "y" ]; then
repo sync -j10
else
echo "you better be sure"
fi
}

clean(){
echo -n "would you like to clean yourself? (y/n)? "
read que

if [ "$que" == "y" ]; then
make clobber && make clean
rm -rf out
cd $HOME
else
echo "you better be sure"
fi
}

# Manifest
manifest() {
cd $HOME
wget https://github.com/rukin5197/android_local_manifest/raw/slim4.2/local_manifest.xml -O .repo/local_manifest.xml
cd $HOME
}

# PMEM
pmem() {
cd $HOME
cd device/htc/primoc
git checkout slim
cd $HOME
}

# Fixes
carrier() {
cd frameworks/base
git fetch https://github.com/rukin5197/frameworks_base-1 refs/heads/jb4.2 && git cherry-pick 58e74ba37f701b96efd9828e466ead1c9204f94d
cd $HOME
cd packages/apps/Settings
git fetch https://github.com/rukin5197/packages_apps_Settings refs/heads/jb4.2 && git cherry-pick 61e3cc81f0ddb44b28814e7ee5f1729b038ab7a9
}

headset() {
cd $HOME
cd frameworks/base
git cherry-pick 27e18942ab8929f8c44c40c84b2f63577d97e280
cd $HOME
}

native() {
cd $HOME
cd frameworks/native
git fetch https://github.com/SlimRoms/frameworks_native refs/heads/jb4.2 && git cherry-pick a5d72b858c1d67f7d857da91177908225aeb23d3
cd $HOME
}

MMS() {
cd $HOME
cd frameworks/opt/telephony
git fetch https://github.com/rukin5197/android_frameworks_opt_telephony refs/heads/cm-10.1 && git cherry-pick 2d80211c50b37390356fd2e9d3844a194cc54948
cd $HOME
}

# Uploads
uploadprimoc() {
cd $HOME
cd out/target/product/primoc
scp -P 2222 Slim-*.zip gannon5197@upload.goo.im:~/public_html/slim/primoc/nightlies/
cd $HOME
}

end() {
END=$(date +%s)
ELAPSED=$((END - START))
E_MIN=$((ELAPSED / 60))
E_SEC=$((ELAPSED - E_MIN * 60))
printf "Elapsed: "
[ $E_MIN != 0 ] && printf "%d min(s) " $E_MIN
printf "%d sec(s)\n" $E_SEC
}

while :
do
clear
manifest;
sync;
clean;
pmem;
MMS;
native;
headset;
carrier;
start;
lunch slim_primoc-userdebug
make -j6 bacon 2>&1 | tee slim_primoc.log
uploadprimoc;
end;
done
