#!/bin/bash
#

HOME=~/android/aokp

cd $HOME

# Uploads
upload() {
cd $HOME
cd out/target/product/triumph
scp -P 2222 aokp_triumph_unofficial_*.zip gannon5197@upload.goo.im:~/public_html/aokp/triumph/nightlies/
}

while :
do
clear
upload;
end;
done
