#!/bin/bash
#

HOME=~/android/cna

cd $HOME

# Set variables to grab zip names
PRIMOC=$(tail cna_primoc.log | cut -f3 -d ' ' | cut -f1 -d ' ' | sed -e '/^$/ d')

REALDATE=`date +%F`

#Upload to goo
scp -P 2222 $PRIMOC gannon5197@upload.goo.im:~/public_html/cna/primoc/nightlies/
exit
